export const SELECT_ITEM = 'SELECT_ITEM';
export const OPEN_DIRECTORY = 'OPEN_DIRECTORY';
export const ADD_NEW_DIRECTORY = 'ADD_NEW_DIRECTORY';
export const ADD_NEW_FILE = 'ADD_NEW_FILE';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const RENAME_ITEM = 'RENAME_ITEM';
export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';